-- Disable Row-Level Security for single-user JTBD Assistant Platform
-- This is appropriate for a single-user application to avoid policy complexity

-- Disable RLS on all tables
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_chunks DISABLE ROW LEVEL SECURITY;
ALTER TABLE insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE jtbds DISABLE ROW LEVEL SECURITY;
ALTER TABLE metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE hmws DISABLE ROW LEVEL SECURITY;
ALTER TABLE solutions DISABLE ROW LEVEL SECURITY;
ALTER TABLE hmws_jtbds DISABLE ROW LEVEL SECURITY;
ALTER TABLE hmws_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE hmws_insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE solutions_hmws DISABLE ROW LEVEL SECURITY;
ALTER TABLE solutions_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE llm_traces DISABLE ROW LEVEL SECURITY;