"""
Constants for the JTBD Assistant Platform core components.
All magic numbers and configuration values are centralized here.
"""

# === EMBEDDING CONSTANTS ===
EMBEDDING_DIMENSION = 1536
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"

# === VECTOR SEARCH CONSTANTS ===
DEFAULT_SIMILARITY_THRESHOLD = 0.7
DEFAULT_SEARCH_LIMIT = 10
MAX_SEARCH_RESULTS = 100

# === CACHE CONSTANTS ===
EMBEDDING_CACHE_SIZE_LIMIT = 10000
CACHE_TTL_HOURS = 24
HASH_ALGORITHM = "sha256"

# === BATCH PROCESSING CONSTANTS ===
MAX_BATCH_SIZE = 100
MAX_CHUNK_SIZE = 1000

# === CONTEXT MANAGEMENT CONSTANTS ===
MAX_CONTEXT_TOKENS = 4000
DEFAULT_TOKEN_BUFFER = 500

# === LLM CONSTANTS ===
DEFAULT_CHAT_MODEL = "gpt-4o-mini"
MAX_RETRIES = 3
BASE_RETRY_DELAY_MS = 1000
MAX_RETRY_DELAY_MS = 10000
BACKOFF_MULTIPLIER = 2.0
DEFAULT_TEMPERATURE = 0.7

# === CONVERSATION CONSTANTS ===
CONVERSATION_TEMPERATURE = 0.8
DISCOVERY_TEMPERATURE = 0.9
MAX_CONVERSATION_HISTORY = 10
MAX_FOLLOW_UP_QUESTIONS = 3
INTENT_CONFIDENCE_THRESHOLD = 0.7

# === LOGGING CONSTANTS ===
PROMPT_TRUNCATE_LENGTH = 2000
RESPONSE_TRUNCATE_LENGTH = 5000
PROMPT_SUMMARY_LENGTH = 100
RESPONSE_SUMMARY_LENGTH = 500

# === DATABASE CONSTANTS ===
CONNECTION_TIMEOUT_SECONDS = 30
MAX_CONNECTION_RETRIES = 3
BATCH_INSERT_SIZE = 1000

# === VALIDATION CONSTANTS ===
MIN_TEXT_LENGTH = 1
MAX_TEXT_LENGTH = 100000
MAX_TITLE_LENGTH = 500
MAX_DESCRIPTION_LENGTH = 10000

# === TABLE NAMES ===
TABLE_DOCUMENTS = "documents"
TABLE_DOCUMENT_CHUNKS = "document_chunks"
TABLE_INSIGHTS = "insights"
TABLE_JTBDS = "jtbds"
TABLE_METRICS = "metrics"
TABLE_HMWS = "hmws"
TABLE_SOLUTIONS = "solutions"
TABLE_LLM_TRACES = "llm_traces"

# === RPC FUNCTION NAMES ===
RPC_SEARCH_CHUNKS = "search_chunks"
RPC_SEARCH_INSIGHTS = "search_insights"
RPC_SEARCH_JTBDS = "search_jtbds"

# === ENVIRONMENT VARIABLE NAMES ===
ENV_SUPABASE_URL = "SUPABASE_URL"
ENV_SUPABASE_KEY = "SUPABASE_KEY"  # Primary key variable
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"

# Alternative environment variable names for flexibility
ENV_SUPABASE_URL_ALTERNATIVES = []  # No alternatives needed
ENV_SUPABASE_KEY_ALTERNATIVES = [
    "SUPABASE_SECRET",  # Alternative service role key name
]

# === ERROR MESSAGES ===
ERROR_CLIENT_NOT_INITIALIZED = "Client not initialized"
ERROR_INVALID_EMBEDDING_DIMENSION = "Invalid embedding dimension"
ERROR_NO_TEXTS_PROVIDED = "No texts provided"
ERROR_EMPTY_TEXT_PROVIDED = "Empty text provided"
ERROR_BATCH_SIZE_EXCEEDED = "Batch size exceeds maximum"
ERROR_NO_CHUNKS_PROVIDED = "No chunks provided"
ERROR_NO_INSIGHTS_PROVIDED = "No insights provided"
ERROR_NO_JTBDS_PROVIDED = "No JTBDs provided"
ERROR_CONNECTION_FAILED = "Connection failed"
ERROR_INSERT_FAILED = "Insert operation failed"
ERROR_UPDATE_FAILED = "Update operation failed"
ERROR_SEARCH_FAILED = "Search operation failed"